export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS_AND_AVATARS = "GET_USERS_AND_AVATARS";
export const GET_USERS_AND_AVATARS_LOADING = "GET_USERS_AND_AVATARS_LOADING";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const GET_ALL_POSTS_LOADING = "GET_ALL_POSTS_LOADING";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";